

import "./cljs-runtime/shadow.module.demo.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.demo.prepend.js");
import "./cljs-runtime/goog.debug.error.js";
SHADOW_ENV.setLoaded("goog.debug.error.js");
import "./cljs-runtime/goog.dom.nodetype.js";
SHADOW_ENV.setLoaded("goog.dom.nodetype.js");
import "./cljs-runtime/goog.asserts.asserts.js";
SHADOW_ENV.setLoaded("goog.asserts.asserts.js");
import "./cljs-runtime/goog.reflect.reflect.js";
SHADOW_ENV.setLoaded("goog.reflect.reflect.js");
import "./cljs-runtime/goog.math.long.js";
SHADOW_ENV.setLoaded("goog.math.long.js");
import "./cljs-runtime/goog.math.integer.js";
SHADOW_ENV.setLoaded("goog.math.integer.js");
import "./cljs-runtime/goog.dom.asserts.js";
SHADOW_ENV.setLoaded("goog.dom.asserts.js");
import "./cljs-runtime/goog.functions.functions.js";
SHADOW_ENV.setLoaded("goog.functions.functions.js");
import "./cljs-runtime/goog.string.typedstring.js";
SHADOW_ENV.setLoaded("goog.string.typedstring.js");
import "./cljs-runtime/goog.string.const.js";
SHADOW_ENV.setLoaded("goog.string.const.js");
import "./cljs-runtime/goog.i18n.bidi.js";
SHADOW_ENV.setLoaded("goog.i18n.bidi.js");
import "./cljs-runtime/goog.html.trustedtypes.js";
SHADOW_ENV.setLoaded("goog.html.trustedtypes.js");
import "./cljs-runtime/goog.html.safescript.js";
SHADOW_ENV.setLoaded("goog.html.safescript.js");
import "./cljs-runtime/goog.fs.url.js";
SHADOW_ENV.setLoaded("goog.fs.url.js");
import "./cljs-runtime/goog.fs.blob.js";
SHADOW_ENV.setLoaded("goog.fs.blob.js");
import "./cljs-runtime/goog.html.trustedresourceurl.js";
SHADOW_ENV.setLoaded("goog.html.trustedresourceurl.js");
import "./cljs-runtime/goog.string.internal.js";
SHADOW_ENV.setLoaded("goog.string.internal.js");
import "./cljs-runtime/goog.html.safeurl.js";
SHADOW_ENV.setLoaded("goog.html.safeurl.js");
import "./cljs-runtime/goog.html.safestyle.js";
SHADOW_ENV.setLoaded("goog.html.safestyle.js");
import "./cljs-runtime/goog.object.object.js";
SHADOW_ENV.setLoaded("goog.object.object.js");
import "./cljs-runtime/goog.html.safestylesheet.js";
SHADOW_ENV.setLoaded("goog.html.safestylesheet.js");
import "./cljs-runtime/goog.dom.htmlelement.js";
SHADOW_ENV.setLoaded("goog.dom.htmlelement.js");
import "./cljs-runtime/goog.dom.tagname.js";
SHADOW_ENV.setLoaded("goog.dom.tagname.js");
import "./cljs-runtime/goog.array.array.js";
SHADOW_ENV.setLoaded("goog.array.array.js");
import "./cljs-runtime/goog.labs.useragent.useragent.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.useragent.js");
import "./cljs-runtime/goog.labs.useragent.util.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.util.js");
import "./cljs-runtime/goog.labs.useragent.browser.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.browser.js");
import "./cljs-runtime/goog.dom.tags.js";
SHADOW_ENV.setLoaded("goog.dom.tags.js");
import "./cljs-runtime/goog.html.safehtml.js";
SHADOW_ENV.setLoaded("goog.html.safehtml.js");
import "./cljs-runtime/goog.html.uncheckedconversions.js";
SHADOW_ENV.setLoaded("goog.html.uncheckedconversions.js");
import "./cljs-runtime/goog.dom.safe.js";
SHADOW_ENV.setLoaded("goog.dom.safe.js");
import "./cljs-runtime/goog.string.string.js";
SHADOW_ENV.setLoaded("goog.string.string.js");
import "./cljs-runtime/goog.collections.maps.js";
SHADOW_ENV.setLoaded("goog.collections.maps.js");
import "./cljs-runtime/goog.structs.structs.js";
SHADOW_ENV.setLoaded("goog.structs.structs.js");
import "./cljs-runtime/goog.uri.utils.js";
SHADOW_ENV.setLoaded("goog.uri.utils.js");
import "./cljs-runtime/goog.uri.uri.js";
SHADOW_ENV.setLoaded("goog.uri.uri.js");
import "./cljs-runtime/goog.string.stringbuffer.js";
SHADOW_ENV.setLoaded("goog.string.stringbuffer.js");
import "./cljs-runtime/cljs.core.js";
SHADOW_ENV.setLoaded("cljs.core.js");
import "./cljs-runtime/clojure.string.js";
SHADOW_ENV.setLoaded("clojure.string.js");
import "./cljs-runtime/clojure.set.js";
SHADOW_ENV.setLoaded("clojure.set.js");
import "./cljs-runtime/shadow.cljs.devtools.client.env.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.env.js");
import "./cljs-runtime/shadow.esm.esm_import$react.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$react.js");
import "./cljs-runtime/clojure.walk.js";
SHADOW_ENV.setLoaded("clojure.walk.js");
import "./cljs-runtime/reagent.debug.js";
SHADOW_ENV.setLoaded("reagent.debug.js");
import "./cljs-runtime/reagent.impl.util.js";
SHADOW_ENV.setLoaded("reagent.impl.util.js");
import "./cljs-runtime/reagent.impl.batching.js";
SHADOW_ENV.setLoaded("reagent.impl.batching.js");
import "./cljs-runtime/reagent.impl.protocols.js";
SHADOW_ENV.setLoaded("reagent.impl.protocols.js");
import "./cljs-runtime/reagent.ratom.js";
SHADOW_ENV.setLoaded("reagent.ratom.js");
import "./cljs-runtime/reagent.impl.component.js";
SHADOW_ENV.setLoaded("reagent.impl.component.js");
import "./cljs-runtime/reagent.impl.input.js";
SHADOW_ENV.setLoaded("reagent.impl.input.js");
import "./cljs-runtime/reagent.impl.template.js";
SHADOW_ENV.setLoaded("reagent.impl.template.js");
import "./cljs-runtime/reagent.core.js";
SHADOW_ENV.setLoaded("reagent.core.js");
import "./cljs-runtime/remix.demo.page.js";
SHADOW_ENV.setLoaded("remix.demo.page.js");
import "./cljs-runtime/shadow.module.demo.append.js";
SHADOW_ENV.setLoaded("shadow.module.demo.append.js");
export let DemoPage = remix.demo.page.demo_page;

shadow.cljs.devtools.client.env.module_loaded("demo");